##############################################################
# Mobile Application Programming (SCSJ3623)
# Semester 2, 2019/2020
##############################################################

# Uncomment the server you want to test out
# Localhost - Change the IP address below to your PC's IP address
@baseUrl = http://192.168.1.7:3000


# REST API Server on Firebase.
# @baseUrl = http://us-central1-eazeetailor.cloudfunctions.net/api

### Getting the list of todos
GET {{baseUrl}}/members

###  Getting a todo of given id
GET {{baseUrl}}/members/e0TIQLOEnYf6AxEglPbd


###  Create a new todo
POST {{baseUrl}}/appointment
Content-Type: application/json

{
     "date" : "2020-12-12",
    "time" : "13:00"
}



### Update the status of a given todo (whether is completed or not)
PATCH {{baseUrl}}/user/0

Content-Type: application/json

{
    "name": "Ina",
    "sleeve" : 20.0,
    "body" : 20.0,
    "chest" : 20.0
}

### Deleting a given todo
DELETE {{baseUrl}}/appointment/3

